export default { 
	tab: {
		index1: 'Home',
		index2: 'Product',
		index3: 'Assets',
		index4: 'Person',
	},
	pageName:{
		index1: "product",
		index2: "Product Details",
		index3: "Draw",
		index4: "Deposit",
		index5: "Authentication",
		index6: "Points Redeen",
		index7: "Help Center",
		index8: "Settings",
		index9: "ID Verificataion",
		index10: "HARVESTER",
	},

    userDrawer:{ //抽屉导航
		data:[
    		{name:'Home'},
    		{name:'Search'},
    		{name:'Category'},
    		{name:'Cart'},
    		{name:'My Favourites'},
    		{name:'Mine'}
		]
	},
	
	
	//-------首页
	index:{
		index1: "Chanjuan",
		index2: "more",
		index3: "Today's Earnings",
		index4: "Yesterday's Earnings",
		index5: "Purchased Pools",
		index6: "Earmings Summary",
		index7: "Recommend Cloud Lottery Package",
		index8: "Start",
		index9: "price",
		index10: "Term",
		index11: "Service Fee",
		index12: "Farmming Power",
		index13: "Sold",
		index14: "Rate Of Return",
		index15: "Static Output",
		index16: "Day",
		index17: "I already know",
		index18: "version update",
		index19: "version number",
		index20: "Update Content",
		index21: "Update now",
		index22: "It has been robbed",
		index23: "Please login first",
		index24: "Loading",
		index25: "Check if your current environment is not Chinese, whether to switch to English",
		index26: "检测您当前环境为中文，是否切换中文",
		index27: "温馨提示",
		index28: "确定",
		index29: "取消",
	},
	//登录
	login: {
		index1: "Mobile phone number",
		index2: "Email address",
		index3: "Password",
		index4: "Remember Password",
		index5: "Forgot Password",
		index6: "Login with Email",
		index7: "Login with mobile phone number",
		index8: "Login",
		index9: "No account yet?",
		index10: "Register now",
		index11: "Read and agree",
		index12: "User Agreement",
		index13: "Please enter your phone number or email",
		index14: "Please reset your password first",
		index15: "Please enter your password",
	},
	//设置资金密码
	resetpaypsd: {
		index1: "Set fund password",
		index2: "Reset Fund Password",
		index3: "Please enter a new password",
		index4: "Please enter the verification code",
		index5: "Please enter the email verification code",
		index6: "Submit",
		index7: "Get verification code",
		index8: "The verification code has been sent, please pay attention to check",
	},
	//注册
	regester: {
		index1: "Register",
		index2: "Username",
		index3: "Phone number",
		index4: "Email address",
		index5: "Verification code",
		index6: "Please fill in the login password",
		index7: "Please enter the invitation code",
		index8: "Register with Email",
		index9: "Use mobile phone number to register",
		index10: "existing account",
		index11: "Login now",
		index12: "Get",
		index13: "To register",
		index14: "Please fill in the phone number or email",
		index15: "Please fill in the username",
		index16: "Please fill in the phone number or email",
		index17: "Please fill in the verification code",
		index18: "Please fill in the password",
		index19: "The verification code has been sent, please pay attention to check",
		index20: "Get verification code",
	},
	//公告
	headlines: {
		index1: "Announcement",
		index2: "View Details",
		index3: "No announcements yet",
		index4: "Notification Details",
	},
	
	
	
	//-------产品
	product: {
		index1: "all",
		index2: "Filter",
		index3: "Start",
		index4: "price",
		index5: "Term",
		index6: "Service Fee",
		index7: "Farmming Power",
		index8: "Sold",
		index9: "Rate Of Return",
		index10: "Static Output",
		index11: "No record yet",
		index12: "Lottery Confirmation Points",
		index13: "All",
		index14: "Package period",
		index15: "Reset",
		index16: "Confirm Filter",
		index17: "Loaded all",
		index18: "Vertical scroll scrollTop value has been modified to 0",
		index19: "It has been robbed",
	},
	//商品详情
	productDetial: {
		index1: "Start",
		index2: "Service Fee",
		index3: "Farmming Power",
		index4: "Sold",
		index5: "Sate Of Return",
		index6: "Static Output",
		index7: "Details of Lucky Draw Package",
		index8: "Lottery Lottery Confirmation Points",
		index9: "Lottery Model",
		index10: "Daily output value",
		index11: "Estimated total output",
		index12: "Estimated total output value",
		index13: "Effective Date",
		index14: "Term",
		index15: "Day",
		index16: "Network rejection rate and technical service fee",
		index17: "Network rejection rate 3% and technical service 2%",
		index18: "Number of copies purchased",
		index19: "positive integer",
		index20: "Description",
		index21: "Please enter payment password",
		index22: "Please enter your password",
		index23: "OK",
		index24: "Cancel",
		index25: "price",
		index26: "Buy Now",
		index27: "Please enter a positive integer",
		index28: "Incorrect quantity entered",
		index29: "The purchase quantity cannot be less than 1",
		index30: "Single purchase cannot exceed 10",
		index31: "Please enter the purchase score",
		index32: "Please set the fund password first",
	},
	
	
	//-------资产
	assets: {
		index1: "Total Assets",
		index2: "Points",
		index3: "Deposit",
		index4: "Withdraw",
		index5: "Asset Details",
		index6: "Available",
		index7: "Pending",
		index8: "Extract",
	},
	//充币
	recharge: {
		index1: "recharge currency",
		index2: "select",
		index3: "Select Channel",
		index4: "Save QR code",
		index5: "Deposit Address",
		index6: "Copy Address",
		index7: "Deposit Record",
		index8: "Save successfully",
		index9: "Save failed",
		index10: "Deposit Record",
		index11: "Amount of deposit",
		index12: "Deposit Address",
		index13: "Account Time",
		index14: "Loaded all",
		index15: "Loading",
		index16: "Loaded all",
	},
	//提币
	withdrawalRecord:{
		index1: "Select",
		index2: "Channel",
		index3: "Address",
		index4: "Amount",
		index5: "Withdraw Amount",
		index6: "All",
		index7: "Available",
		index8: "Actual Receipt",
		index9: "Withdraw password",
		index10: "Enter withdraw password",
		index11: "Verification Code",
		index12: "Enter verification code",
		index13: "Handling Fee",
		index14: "Confirm",
		index15: "Enter address here",
		index16: "Withdraw Record",
		index17: "Ready to scan",
		index18: "Scanning",
		index19: "Cancel",
		index20: "Failed to read",
		index21: "Loading",
		index22: "Loaded all",
		index23: "Scan",
		index24: "The device does not support NFC!",
		index25: "Please enable the NFC function in the system settings first!",
		index26: "Casting succeeded",
		//
		index27: "Please enter the withdrawal address",
		index28: "Please enter the withdrawal amount",
		index29: "Lower than the minimum withdrawal amount",
		index30: "Exceeded the maximum withdrawal amount",
		index31: "Exceeds the current number of possessions",
		index32: "Please enter the verification code",
		index33: "Please enter the fund password",
	},
	//提币记录
	carryRecord: {
		index1: "withdrawal amount",
		index2: "Handling fee",
		index3: "Deposit Address",
		index4: "withdrawal time",
		index5: "Under review",
		index6: "Waiting to release coins",
		index7: "Failed",
		index8: "Success",
		index9: "Transferring",
		index10: "Failed to withdraw from risk control",
		index11: "Insufficient hot wallet balance",
	},
	//积分
	recordList: {
		index1: "Record Points",
		index2: "Collect",
		index3: "Transfer",
		index4: "Redeem",
		index5: "Transfer Record",
		index6: "Collect Record",
		index7: "Asset Flow",
	},
	//收积分
	userRecharge: {
		index1: "Select",
		index2: "Transfer Points",
		index3: "Scan QR code to collect",
		index4: "Shaolin Points",
	},
	//付积分
	extract: {
		index1: "Transfer Points",
		index2: "Select Channel",
		index3: "Amount",
		index4: "Enter amount here",
		index5: "available",
		index6: "Actual arrival",
		index7: "Address",
		index8: "Enter address to transfer",
		index9: "Verification Code",
		index10: "Funding Password",
		index11: "Fees",
		index12: "Remarks",
		index13: "Enter a note here",
		index14: "Confirm Transfer",
		index15: "The number of USDT withdrawal points is greater than 10",
		index16: "The number of credits for MSL confirmation is greater than 0.1",
		index17: "Please enter the number of withdrawals",
		index18: "Please enter the address to confirm the right of credit",
		index19: "Please enter the verification code",
		index20: "Please enter the fund password",
		index21: "Pay All",
	},
	//积分消费
	consume: {
		index0: "Redeem Points",
		index1: "Amount",
		index2: "record",
		index3: "Enter amount here",
		index4: "Address",
		index5: "Enter address to redeem",
		index6: "Available consumption balance",
		index7: "Confirm Redeem",
		index8: "The input amount cannot be empty",
		index9: "Insufficient balance",
		index10: "Please enter the correct address",
		index11: "Successful consumption",
		index12: "Error getting QR code",
	},
	//付积分记录
	userRecord: {
		index1: "Withdrawal succeeded",
		index2: "Withdrawal exception",
		index3: "To be transferred",
		index4: "The address of the other party to receive points",
		index5: "Payment time",
		index6: "No record yet",
		index7: "Loaded all",
	},
	//收积分记录
	relist: {
		index0: "Collect Points Record",
		index1: "Quantity",
		index2: "Address",
		index3: "Pull up to show more",
		index4: "Loading...",
		index5: "No more",
	},
	//资产流水
	assetsRecord: {
		index1: "Asset Flow",
		index2: "Filter records",
		index3: "Order ID",
		index4: "time",
		index5: "No record yet",
		index6: "All",
		index7: "Manual recharge",
		index8: "Buy Winning Power",
		index9: "Winning Power Income",
		index10: "Invitation Reward",
		index11: "Team Rewards",
		index12: "Points Redeem",
		index13: "Consumption Income",
	},
	
	
	
	//-------个人
	user: {
		index1: "Go to login",
		index2: "ID",
		index3: "Copy",
		index4: "My Harvester",
		index5: "My Earnings",
		index6: "My Harvester",
		index7: "MSL Total Farmming Power",
		index8: "Farmming",
		index9: "Authentication",
		index10: "Unauthenticated",
		index11: "Pending review",
		index12: "Authenticated",
		index13: "Points Redeem",
		index14: "merchant QR code",
		index15: "My Team",
		index16: "Digital RMB e-CNY reserved interface",
		index17: "Invite",
		index18: "Contact Us",
		index19: "Help Center",
		index20: "Settings",
		index21: "Logout",
		index22: "Contact Us",
		index23: "Phone",
		index24: "Mailbox",
		index25: "WeChat",
		index26: "I know",
		index27: "Apply",
		index28: "Copy successfully",
		index29: "Jump to",
		index30: "Are you sure you want to log out",
		index31: "stay tuned",
	},
	//实名认证
	authen: {
		index1: "legal Name",
		index2: "Please enter your legal Name",
		index3: "ID Num",
		index4: "Please enter the ID number",
		index5: "Upload Documents",
		index6: "Submit",
		index7: "Note: Please input carefully, the information can not be changed after verified.",
		index8: "Please enter your real name",
		index9: "Please enter the ID number",
		index10: "Please upload the front of the ID card",
		index11: "Please upload the reverse side of the ID card",
		index12: "Please hold your ID photo",
		index13: "Submitted successfully",
		index14: "Front Side",
		index15: "Back Side",
		index16: "Photo witn holding ID",
	},
	//积分消费
	point: {
		index1: "Scan QR Code of address",
		index2: "Phone Number",
		index3: "Enter phone number here",
		index4: "Transfer Amount",
		index5: "Enter the amount here",
		index6: "Available",
		index7: "Remarks",
		index8: "Confirm Transfer",
		index9: "Caution: Only either the address or phone number it to transfer the points please do not enter both of them",
		index10: "Please enter the amount of transfer points",
		index11: "OK",
		index12: "Cancel",
		index13: "Transfer result",
		index14: "Transfer successful",
		index15: "Scan QR code to pay me",
		index16: "Error getting QR code",
		index17: "Cancelled",
		index18: "The input amount cannot be negative",
		index19: "The input amount cannot be empty",
		index20: "The phone number is incorrect",
	},
	//我的团队
	team: {
		index1: "My Team",
		index2: "Total of team members",
		index3: "Username",
		index4: "Account",
		index5: "level",
		index6: "Hierarchy",
	},
	//邀请好友
	invite: {
		index1: "Invite friends",
		index2: "My invitation code",
		index3: "Copy",
		index4: "Scan and download Meta Smart Link",
	},
	//帮助中心
	help: {
		index1: "View Details",
		index2: "No announcements yet",
	},
	//设置
	set: {
		index1: "Photo",
		index2: "User Name",
		index3: "Change Phone Number",
		index4: "Change Email",
		index5: "Login password",
		index6: "Withdraw Password",
		index7: "Version",
		index8: "V",
		index9: "Logout",
		index10: "Set Nickname",
		index11: "Please enter a nickname",
		index12: "OK",
		index13: "Cancel",
		index14: "Please enter a nickname to modify",
		index15: "Uploading",
		index16: "Cancelled",
		index17: "Are you sure you want to log out",
		index18: "Open",
		index19: "close",
		index20: "Message Push",
		index21: "Withdraw Password",
		index22: "Are you sure to cancel the account",
		index23: "Cancel Account",
		index24: "OK",
		index25: "Cancel",
		index26: "The following risks are involved in account cancellation:",
		index27: "1. Permanent logoff cannot be retrieved",
		index28: "2. All product data will not be retrieved",
	},
	//我的订单
	myrecord: {
		index1: "name",
		index2: "Effective",
		index3: "terminate",
		index4: "Not valid",
		index5: "No record yet",
		index6: "Loaded all",
	},
	//修改登录密码
	findpsd: {
		index1: "Modify login password",
		index2: "Old password",
		index3: "New password",
		index4: "Verification code",
		index5: "Email verification code",
		index6: "Submit",
		index7: "Forgot Password",
		index8: "Get",
		index9: "The verification code has been sent, please pay attention to check",
		index10: "Get",
		index11: "Verification Code",
		//
		index12: "Please enter the old password",
		index13: "Please enter a new password",
		index14: "Please enter the verification code",
	},
	//重置登录密码
	forgetpsd: {
		index1: "Reset login password",
		index2: "Mobile phone number",
		index3: "Email address",
		index4: "Verification code",
		index5: "New password",
		index6: "Confirm new password",
		index7: "Modify email login password",
		index8: "Modify mobile phone login password",
		index9: "Submit",
		index10: "Get",
		index11: "Enter the wrong password again",
		index12: "Network exception",
		index13: "Please enter your phone number or email",
	},
	//修改资金密码
	updatepaypsd: {
		index1: "Modify Fund Password",
		index2: "Forgot the fund password",
	},
	//修改手机号
	getmessages: {
		index1: "Updata Phone",
		index2: "Updata Email",
		index3: "New mobile number",
		index4: "New email address",
		index5: "Login Password",
		index6: "Pre-email verification code",
		index7: "New email verification code",
		index8: "Please enter the account number",
		index9: "Please enter the login password",
		index10: "Account cannot be empty",
		index11: "Please enter a new mailbox first",
	},
 }
