export default { 
	tab: {
		index1: "首页",
		index2: "产品",
		index3: "资产",
		index4: "个人",
	},
	pageName:{
		index1: "产品",
		index2: "产品详情",
		index3: "提币",
		index4: "充币",
		index5: "实名认证",
		index6: "积分消费",
		index7: "帮助中心",
		index8: "设置",
		index9: "实名认证",
		index10: "产品",
	},

    userDrawer:{ //抽屉导航
		data:[
			{name:"首页"},
			{name:"搜索"},
			{name:"分类"},
			{name:"购物车"},
			{name:"收藏"},
			{name:"我的"}
		]
	},
	
	
	//-------首页
	index:{
		index1: "婵娟",
		index2: "更多",
		index3: "今日收益",
		index4: "昨日收益",
		index5: "已购买中奖力",
		index6: "累计产出",
		index7: "推荐云抽奖套餐",
		index8: "生效日期",
		index9: "价格",
		index10: "期限",
		index11: "中奖力服务费",
		index12: "中奖力",
		index13: "已售",
		index14: "静态年化收益率",
		index15: "静态产出",
		index16: "天",
		index17: "我已知晓",
		index18: "版本更新",
		index19: "版本号",
		index20: "更新内容",
		index21: "立即更新",
		index22: "已经被抢光啦",
		index23: "请先登录",
		index24: "加载中",
		index25: "检测您当前环境非中文，是否切换英文",
		index26: "Check if your current environment is Chinese, whether to switch Chinese",
		index27: "Kind Tips",
		index28: "OK",
		index29: "Cancel",
	},
	//登录
	login: {
		index1: "请输入手机号码",
		index2: "请输入邮箱",
		index3: "请输入密码",
		index4: "记住密码",
		index5: "忘记密码",
		index6: "使用邮箱登陆",
		index7: "使用手机号登陆",
		index8: "登录",
		index9: "还没有账户？",
		index10: "马上注册",
		index11: "已阅读并同意",
		index12: "用户协议",
		index13: "请输入手机号或邮箱",
		index14: "请先重置密码",
		index15: "请输入密码",
	},
	//设置资金密码
	resetpaypsd: {
		index1: "设置资金密码",
		index2: "重置资金密码",
		index3: "请输入新密码",
		index4: "请输入验证码",
		index5: "请输入邮箱验证码",
		index6: "提交",
		index7: "获取验证码",
		index8: "验证码已发送，请注意查收",
	},
	//注册
	regester: {
		index1: "注册",
		index2: "请输入用户名",
		index3: "请输入手机号码",
		index4: "请输入邮箱",
		index5: "请输入验证码",
		index6: "请填写登录密码",
		index7: "请输入邀请码",
		index8: "使用邮箱注册",
		index9: "使用手机号注册",
		index10: "已有账户",
		index11: "马上登录",
		index12: "获取验证码",
		index13: "去注册",
		index14: "请填写手机号或邮箱",
		index15: "请填写用户名",
		index16: "请填写手机号或邮箱",
		index17: "请填写验证码",
		index18: "请填写密码",
		index19: "验证码已发送，请注意查收",
		index20: "获取验证码",
	},
	//公告
	headlines: {
		index1: "公告",
		index2: "查看详情",
		index3: "暂无公告",
		index4: "通知详情",
	},
	
	
	
	//-------产品
	product: {
		index1: "全部",
		index2: "筛选",
		index3: "生效日期",
		index4: "价格",
		index5: "期限",
		index6: "中奖力服务费",
		index7: "中奖力",
		index8: "已售",
		index9: "静态年化收益率",
		index10: "静态产出",
		index11: "暂无记录",
		index12: "抽奖确权积分",
		index13: "全部",
		index14: "套餐期限",
		index15: "重置",
		index16: "确认筛选",
		index17: "已加载全部",
		index18: "纵向滚动 scrollTop 值已被修改为 0",
		index19: "已经被抢光啦",
	},
	//商品详情
	productDetial: {
		index1: "生效日期",
		index2: "中奖力服务费",
		index3: "中奖力",
		index4: "已售",
		index5: "静态年化收益率",
		index6: "静态产出",
		index7: "抽奖套餐详情",
		index8: "抽奖确权积分",
		index9: "抽奖机型",
		index10: "单日产出值",
		index11: "预计总产出",
		index12: "预计产出总价值",
		index13: "生效日期",
		index14: "期限",
		index15: "天",
		index16: "网络拒绝率及技术服务费",
		index17: "网络拒绝率3%及技术服务2%",
		index18: "购买份数",
		index19: "正整数",
		index20: "说明",
		index21: "请输入支付密码",
		index22: "请输入密码",
		index23: "确定",
		index24: "取消",
		index25: "价格",
		index26: "立即购买",
		index27: "请输入正整数",
		index28: "输入数量有误",
		index29: "购买数量不能小于1",
		index30: "单次购买不能超过10",
		index31: "请输入购买分数",
		index32: "请先设置资金密码",
	},
	
	
	//-------资产
	assets: {
		index1: "总资产",
		index2: "积分",
		index3: "充币",
		index4: "提币",
		index5: "资产明细",
		index6: "可用",
		index7: "冻结",
		index8: "点击提取",
	},
	//充币
	recharge: {
		index1: "充值币种",
		index2: "选择",
		index3: "选择通道",
		index4: "保存二维码",
		index5: "充币地址",
		index6: "复制地址",
		index7: "充币记录",
		index8: "保存成功",
		index9: "保存失败",
		index10: "充币记录",
		index11: "充币数量",
		index12: "充币地址",
		index13: "到账时间",
		index14: "已加载全部",
		index15: "加载中",
		index16: "已加载全部",
	},
	//提币
	withdrawalRecord:{
		index1:"选择币种",
		index2:"选择通道",
		index3:"提币地址",
		index4:"数量",
		index5:"请输入提币数量",
		index6:"全部",
		index7:"可用",
		index8:"实际到账",
		index9:"资金密码",
		index10:"请输入资金密码",
		index11:"验证码",
		index12:"请输入验证码",
		index13:"手续费",
		index14:"确认",
		index15:"请输入提币地址",
		index16: "提币记录",
		index17: "已准备好扫描",
		index18: "正在扫描",
		index19: "取消",
		index20: "读取失败",
		index21: "加载中",
		index22: "已加载全部",
		index23: "扫描",
		index24: "设备不支持NFC！",
		index25: "请在系统设置中先启用NFC功能！",
		index26: "铸造成功",
		//
		index27: "请输入提币地址",
		index28: "请输入提币数量",
		index29: "低于最小提币量",
		index30: "超过最大提币量",
		index31: "超过当前拥有数量",
		index32: "请输入验证码",
		index33: "请输入资金密码",
	},
	//提币记录
	carryRecord: {
		index1: "提币数量",
		index2: "手续费",
		index3: "充币地址",
		index4: "提币时间",
		index5: "审核中",
		index6: "等待放币",
		index7: "失败",
		index8: "成功",
		index9: "转账中",
		index10: "风控提现失败",
		index11: "热钱包余额不足",
	},
	//积分
	recordList: {
		index1: "记录",
		index2: "收积分",
		index3: "付积分",
		index4: "积分消费",
		index5: "付积分记录",
		index6: "收积分记录",
		index7: "资产流水",
	},
	//收积分
	userRecharge: {
		index1: "选择",
		index2: "婵娟积分",
		index3: "扫描二维码充值",
		index4: "少林积分",
	},
	//付积分
	extract: {
		index1: "婵娟积分",
		index2: "选择通道",
		index3: "支付数量",
		index4: "请输入支付数量",
		index5: "可用",
		index6: "实际到账",
		index7: "对方收积分地址",
		index8: "请输入对方收积分地址",
		index9: "验证码",
		index10: "资金密码",
		index11: "手续费",
		index12: "备注",
		index13: "请输入备注",
		index14: "确认付积分",
		index15: "USDT提确权积分数量大于10",
		index16: "MSL提确权积分数量大于0.1",
		index17: "请输入提取数量",
		index18: "请输入提确权积分地址",
		index19: "请输入验证码",
		index20: "请输入资金密码",
		index21: "全部支付",
	},
	//积分消费
	consume: {
		index0: "积分消费",
		index1: "消费数量",
		index2: "记录",
		index3: "请输入消费数量",
		index4: "消费接收地址",
		index5: "请输入消费接收地址",
		index6: "可用消费余额",
		index7: "确认消费",
		index8: "输入金额不能为空",
		index9: "余额不足",
		index10: "请输入正确地址",
		index11: "消费成功",
		index12: "二维码获取错误",
	},
	//付积分记录
	userRecord: {
		index1: "提现成功",
		index2: "提现异常",
		index3: "待转账",
		index4: "对方收积分地址",
		index5: "支付时间",
		index6: "暂无记录",
		index7: "已加载全部",
	},
	//收积分记录
	relist: {
		index0: "收积分记录",
		index1: "数量",
		index2: "地址",
		index3: "上拉显示更多",
		index4: "正在加载...",
		index5: "没有更多数据了",
	},
	//资产流水
	assetsRecord: {
		index1: "资产流水",
		index2: "筛选记录",
		index3: "订单ID",
		index4: "时间",
		index5: "暂无记录",
		index6: "全部",
		index7: "人工充值",
		index8: "购买中奖力",
		index9: "中奖力收益",
		index10: "邀请奖励",
		index11: "团队奖励",
		index12: "积分消费",
		index13: "消费收入",
	},
	
	
	
	//-------个人
	user: {
		index1: "去登录",
		index2: "ID号码",
		index3: "复制",
		index4: "我的订单",
		index5: "我的收益",
		index6: "我的套餐",
		index7: "MSL总中奖力",
		index8: "个生效中",
		index9: "实名认证",
		index10: "未认证",
		index11: "待审核",
		index12: "已认证",
		index13: "积分消费",
		index14: "商家二维码",
		index15: "我的团队",
		index16: "数字人民币e-CNY预留接口",
		index17: "邀请好友",
		index18: "联系我们",
		index19: "帮助中心",
		index20: "设置",
		index21: "退出登录",
		index22: "联系我们",
		index23: "电话",
		index24: "邮箱",
		index25: "微信",
		index26: "我知道了",
		index27: "申请",
		index28: "复制成功",
		index29: "跳转到",
		index30: "确定要退出登录么",
		index31: "敬请期待",
	},
	//实名认证
	authen: {
		index1: "用户名",
		index2: "请输入真实姓名,认证后不可更改",
		index3: "身份证号",
		index4: "请输入真实姓名对应的身份证号",
		index5: "上传证件资料",
		index6: "确认提交",
		index7: "注：认证信息一经认证，不可修改，请认真填写",
		index8: "请输入真实姓名",
		index9: "请输入身份证号",
		index10: "请上传身份证正面",
		index11: "请上传身份证反面",
		index12: "请上手持身份证照",
		index13: "提交成功",
		index14: "身份证正面",
		index15: "身份证反面",
		index16: "手持身份证",
	},
	//积分消费
	point: {
		index1: "扫一扫转积分",
		index2: "手机号转积分",
		index3: "请输入商家手机号进行转积分",
		index4: "转账积分数额",
		index5: "请输入转账积分数额",
		index6: "可用消费余额",
		index7: "备注内容",
		index8: "确认转积分",
		index9: "特别提醒：扫一扫转积分和手机号转积分是二选一，而不是均需要输入",
		index10: "请输入转账积分数额",
		index11: "确定",
		index12: "取消",
		index13: "转账结果",
		index14: "转账成功",
		index15: "扫描二维码向我付款",
		index16: "二维码获取错误",
		index17: "已取消",
		index18: "输入金额不能为负数",
		index19: "输入金额不能为空",
		index20: "手机号有误",
	},
	//我的团队
	team: {
		index1: "我的团队",
		index2: "团队总人数",
		index3: "用户名",
		index4: "账户",
		index5: "等级",
		index6: "代数",
	},
	//邀请好友
	invite: {
		index1: "邀请好友",
		index2: "我的邀请码",
		index3: "复制",
		index4: "扫描下载元慧链",
	},
	//帮助中心
	help: {
		index1: "查看详情",
		index2: "暂无公告",
	},
	//设置
	set: {
		index1: "头像",
		index2: "用户名",
		index3: "修改手机号",
		index4: "修改邮箱号",
		index5: "修改登录密码",
		index6: "设置资金密码",
		index7: "当前版本",
		index8: "版本号",
		index9: "退出登录",
		index10: "设置昵称",
		index11: "请输入昵称",
		index12: "确定",
		index13: "取消",
		index14: "请输入修改昵称",
		index15: "上传中",
		index16: "已取消",
		index17: "确定要退出登录么",
		index18: "打开",
		index19: "关闭",
		index20: "消息推送",
		index21: "修改资金密码",
		index22: "是否确定注销账号",
		index23: "注销账号",
		index24: "确定",
		index25: "取消",
		index26: "注销账号有以下风险:",
		index27: "1.永久注销无法找回",
		index28: "2.所有产品数据将无法找回",
	},
	//我的订单
	myrecord: {
		index1: "名称",
		index2: "已生效",
		index3: "终止",
		index4: "未生效",
		index5: "暂无记录",
		index6: "已加载全部",
	},
	//修改登录密码
	findpsd: {
		index1: "修改登录密码",
		index2: "请输入旧密码",
		index3: "请输入新密码",
		index4: "请输入验证码",
		index5: "请输入邮箱验证码",
		index6: "提交",
		index7: "忘记密码",
		index8: "获取验证码",
		index9: "验证码已发送，请注意查收",
		index10: "获取验证码",
		index11: "验证码",
		//
		index12: "请输入旧密码",
		index13: "请输入新密码",
		index14: "请输入验证码",
	},
	//重置登录密码
	forgetpsd: {
		index1: "重置登录密码",
		index2: "请输入手机号码",
		index3: "请输入邮箱",
		index4: "请输入验证码",
		index5: "请输入新密码",
		index6: "确认新密码",
		index7: "修改邮箱登陆密码",
		index8: "修改手机登陆密码",
		index9: "提交",
		index10: "获取验证码",
		index11: "再次输入密码错误",
		index12: "网路异常",
		index13: "请输入手机号或邮箱",
	},
	//修改资金密码
	updatepaypsd: {
		index1: "修改资金密码",
		index2: "忘记资金密码",
	},
	//修改手机号
	getmessages: {
		index1: "修改手机号",
		index2: "修改邮箱号",
		index3: "请输入新手机号码",
		index4: "请输入新邮箱",
		index5: "登录密码(大小写字母/数字组合)",
		index6: "请输旧邮箱验证码",
		index7: "请输入新邮箱验证码",
		index8: "请输入账号",
		index9: "请输入登录密码",
		index10: "账号不能为空",
		index11: "请先输入新邮箱",
	},
	
	
	
	
	
	
	
	
	
	
	
	
	
	//页面title
	page: {
		page1: "产品",
	},
 }
